version = 1

[[input]]
id = "xor"
scenarios = [
  "orca2_single",
  "256cube_single",
  "medfmt_single",
  "smallepoch_single",
  "smallepoch_4shards",
  "orca2_multiscale",
  "256cube_multiscale",
  "medfmt_multiscale",
  "orca2_multiscale_dim0",
  "256cube_multiscale_dim0",
  "medfmt_multiscale_dim0",
]
default_scenario = "orca2_single"

[[input]]
id = "zeros"
scenarios = ["orca2_single", "256cube_single"]
default_scenario = "orca2_single"

[[input]]
id = "rand"
scenarios = ["orca2_single", "256cube_single"]
default_scenario = "orca2_single"

[[input]]
id = "opencell-dna"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[input]]
id = "opencell-protein"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[input]]
id = "bbbc010-brightfield"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[input]]
id = "jump-scope-fluorescence"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[input]]
id = "dynacell-a549-phase"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[input]]
id = "cosem-cos7-em"
scenarios = ["microscopy"]
default_scenario = "microscopy"

[[scenario]]
id = "orca2_single"
inputs = ["xor", "zeros", "rand"]
default_input = "xor"

[[scenario]]
id = "256cube_single"
inputs = ["xor", "zeros", "rand"]
default_input = "xor"

[[scenario]]
id = "medfmt_single"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "smallepoch_single"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "smallepoch_4shards"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "orca2_multiscale"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "256cube_multiscale"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "medfmt_multiscale"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "orca2_multiscale_dim0"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "256cube_multiscale_dim0"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "medfmt_multiscale_dim0"
inputs = ["xor"]
default_input = "xor"

[[scenario]]
id = "microscopy"
inputs = [
  "opencell-dna",
  "opencell-protein",
  "bbbc010-brightfield",
  "jump-scope-fluorescence",
  "dynacell-a549-phase",
  "cosem-cos7-em",
]
default_input = "opencell-dna"
